management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"

    gateway:
      enabled: true

spring.application.name: gate-way

spring:
  cloud:
    gateway:
#      httpclient:
#        connect-timeout: 10000
#        response-timeout: 1s
      routes:
        - id: order-service
          uri: http://127.0.0.1:8181
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/(?<path>.*),/$\{path}

        - id: cart-service
          uri: http://127.0.0.1:8181
          predicates:
            - Path=/cart/**
          filters:
            - RewritePath=/cart/(?<path>.*),/$\{path}
            - name: Retry
              args:
                retries: 3
                statuses: INTERNAL_SERVER_ERROR
                methods: GET
                backoff:
                  firstBackoff: 1000ms
                  maxBackoff: 6000ms
                  factor: 2
                  basedOnPreviousValue: false
          metadata:
             connect-timeout: 10000
             response-timeout: 1000
      default-filters:
        - name: CustomFilter
          args:
            baseMessage: Spring Cloud Gateway CustomFilter1
            preLogger: true
            postLogger: true
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/


logging:
  level:
    root: info
    com.doli.gateway.filter.CustomFilter: debug

